const S={w:[],t:{},i:0,done:new Set(JSON.parse(localStorage.getItem("wbDone")||"[]")),timer:0,q:[],n:0,score:0,answered:false};const $=s=>document.querySelector(s),mix=a=>[...a].sort(()=>Math.random()-.5);
function stop(){clearTimeout(S.timer);["#wordPlayer","#sentencePlayer"].forEach(x=>$(x).pause());document.querySelectorAll(".audio").forEach(x=>x.classList.remove("playing"))}
function play(type,id,b){stop();let a=$(type==="word"?"#wordPlayer":"#sentencePlayer"),t=S.t[id][type];a.currentTime=t.start;a.play().then(()=>{b.classList.add("playing");S.timer=setTimeout(()=>{a.pause();b.classList.remove("playing")},(t.end-t.start)*1000)}).catch(()=>b.textContent="다시 눌러 재생")}
function render(){stop();let w=S.w[S.i],done=S.done.has(w.id);$("#counter").textContent=w.id+" / 30";$("#word").textContent=w.word;$("#meaning").textContent=(w.pos?w.pos+" ":"")+w.meaning;$("#definition").textContent=w.definition;$("#example").textContent=w.example;$("#translation").textContent=w.translation;$("#completeBtn").classList.toggle("done",done);$("#completeBtn").textContent=done?"✓ 학습 완료":"○ 학습 완료";$("#progress").textContent=S.done.size+" / 30 학습"}
function tab(n){stop();$("#learnPanel").hidden=n!=="learn";$("#quizPanel").hidden=n!=="quiz";document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===n))}
function question(w,n){let type=n%3,label,q,audio=false;if(type===0){label="영영풀이";q=w.definition}else if(type===1){label="예문 완성";q=w.example.replace(new RegExp(w.word.replace(" ","\\s+"),"i"),"________")}else{label="발음 듣기";q="들은 단어를 고르세요.";audio=true}return{w,label,q,audio,answer:w.word,choices:mix([w.word,...mix(S.w.filter(x=>x.id!==w.id)).slice(0,3).map(x=>x.word)])}}
function start(){S.q=mix(S.w).slice(0,10).map(question);S.n=S.score=0;$("#quizStart").hidden=$("#result").hidden=true;$("#quizBox").hidden=false;show()}
function show(){stop();S.answered=false;let x=S.q[S.n];$("#quizCount").textContent=S.n+1+" / 10";$("#score").textContent="점수 "+S.score;$("#quizLabel").textContent=x.label;$("#question").textContent=x.q;$("#feedback").textContent="";$("#feedback").className="feedback";$("#nextQuestion").hidden=true;$("#quizAudio").hidden=!x.audio;$("#choices").innerHTML=x.choices.map(c=>'<button class="choice">'+c+"</button>").join("");if(x.audio)setTimeout(()=>play("word",x.w.id,$("#quizAudio")),250)}
function answer(b){if(S.answered)return;S.answered=true;let x=S.q[S.n],ok=b.textContent===x.answer;if(ok){S.score++;b.classList.add("correct");$("#feedback").textContent="정답이에요!";$("#feedback").classList.add("ok")}else{b.classList.add("wrong");[...document.querySelectorAll(".choice")].find(y=>y.textContent===x.answer).classList.add("correct");$("#feedback").textContent="정답은 "+x.answer+"예요.";$("#feedback").classList.add("no")}$("#score").textContent="점수 "+S.score;$("#nextQuestion").hidden=false;document.querySelectorAll(".choice").forEach(y=>y.disabled=true)}
function finish(){stop();$("#quizBox").hidden=true;$("#result").hidden=false;$("#resultScore").textContent=S.score+" / 10";$("#resultMessage").textContent=S.score>=8?"잘했어요! 다음 학습으로 넘어가도 좋아요.":"틀린 단어를 다시 학습한 뒤 한 번 더 풀어 보세요."}
async function init(){[S.w,S.t]=await Promise.all([fetch("words.json").then(r=>r.json()),fetch("assets/audio/audio-timings.json").then(r=>r.json())]);render();document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>tab(b.dataset.tab));$("#prev").onclick=()=>{S.i=(S.i+29)%30;render()};$("#next").onclick=()=>{S.i=(S.i+1)%30;render()};$("#random").onclick=()=>{S.i=Math.floor(Math.random()*30);render()};$("#completeBtn").onclick=()=>{let id=S.w[S.i].id;S.done.has(id)?S.done.delete(id):S.done.add(id);localStorage.setItem("wbDone",JSON.stringify([...S.done]));render()};$("#wordAudio").onclick=()=>play("word",S.w[S.i].id,$("#wordAudio"));$("#sentenceAudio").onclick=()=>play("sentence",S.w[S.i].id,$("#sentenceAudio"));$("#startQuiz").onclick=$("#retry").onclick=start;$("#quizAudio").onclick=()=>play("word",S.q[S.n].w.id,$("#quizAudio"));$("#choices").onclick=e=>e.target.matches(".choice")&&answer(e.target);$("#nextQuestion").onclick=()=>++S.n<10?show():finish()}init().catch(()=>document.body.innerHTML="<p>학습 자료를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.</p>");