let words=[],timings={},current=0,stopTimer=null,quiz=[],qi=0,points=0,answered=false;const $=s=>document.querySelector(s);const completed=new Set(JSON.parse(localStorage.getItem("wb-completed")||"[]"));const wordPlayer=$("#wordPlayer"),sentencePlayer=$("#sentencePlayer");
function save(){localStorage.setItem("wb-completed",JSON.stringify([...completed]))}
function stopAudio(){clearTimeout(stopTimer);[wordPlayer,sentencePlayer].forEach(a=>{a.pause()});document.querySelectorAll(".audio").forEach(b=>b.classList.remove("playing"))}
function playSegment(player,range,button){stopAudio();player.currentTime=range.start;button.classList.add("playing");player.play().catch(()=>{});stopTimer=setTimeout(()=>{player.pause();button.classList.remove("playing")},Math.max(200,(range.end-range.start)*1000))}
function render(){const w=words[current];$("#number").textContent=(current+1)+" / "+words.length;$("#word").textContent=w.word;$("#meaning").textContent=w.meaning;$("#definition").textContent=(w.pos?w.pos+" ":"")+w.definition;$("#example").textContent=w.example;$("#translation").textContent=w.translation;const done=completed.has(w.id);$("#complete").textContent=done?"✓ 학습 완료":"○ 학습 완료";$("#complete").classList.toggle("done",done);$("#progress").textContent=completed.size+"/30";$("#meterBar").style.width=((current+1)/words.length*100)+"%";stopAudio()}
function setTab(name){document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===name));document.querySelectorAll(".panel").forEach(p=>p.classList.toggle("active",p.id===name));stopAudio()}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$("#prev").onclick=()=>{current=(current-1+words.length)%words.length;render()};$("#next").onclick=()=>{current=(current+1)%words.length;render()};$("#random").onclick=()=>{current=Math.floor(Math.random()*words.length);render()};$("#complete").onclick=()=>{const id=words[current].id;completed.has(id)?completed.delete(id):completed.add(id);save();render()};$("#wordAudio").onclick=()=>playSegment(wordPlayer,timings[words[current].id].word,$("#wordAudio"));$("#sentenceAudio").onclick=()=>playSegment(sentencePlayer,timings[words[current].id].sentence,$("#sentenceAudio"));
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function mask(sentence,word){return sentence.replace(new RegExp(word.replace(" ","\\s+"),"i"),"________")}
function makeQuestion(w,i){const type=i%3,others=shuffle(words.filter(x=>x.id!==w.id)).slice(0,3),options=shuffle([w,...others]);if(type===0)return{type:"영영 풀이",q:w.definition,answer:w.word,options};if(type===1)return{type:"예문",q:mask(w.example,w.word),answer:w.word,options};return{type:"발음 듣기",q:"음성을 듣고 알맞은 단어를 고르세요.",answer:w.word,options,audio:true,id:w.id}}
function startQuiz(){quiz=shuffle(words).slice(0,10).map(makeQuestion);qi=0;points=0;$("#quizIntro").classList.add("hidden");$("#quizResult").classList.add("hidden");$("#quizPlay").classList.remove("hidden");showQuestion()}
function showQuestion(){answered=false;const q=quiz[qi];$("#quizCount").textContent=(qi+1)+" / 10";$("#score").textContent=points+"점";$("#quizMeter").style.width=(qi/10*100)+"%";$("#quizType").textContent=q.type;$("#question").textContent=q.q;$("#feedback").textContent="";$("#feedback").className="feedback";$("#nextQuestion").classList.add("hidden");$("#quizAudio").classList.toggle("hidden",!q.audio);$("#choices").innerHTML=q.options.map(o=>'<button class="choice" data-answer="'+o.word.replace(/"/g,"&quot;")+'">'+o.word+"</button>").join("");if(q.audio)setTimeout(()=>playSegment(wordPlayer,timings[q.id].word,$("#quizAudio")),200)}
$("#choices").onclick=e=>{if(!e.target.matches(".choice")||answered)return;answered=true;const q=quiz[qi],picked=e.target.dataset.answer,ok=picked===q.answer;if(ok)points+=10;document.querySelectorAll(".choice").forEach(b=>{b.disabled=true;if(b.dataset.answer===q.answer)b.classList.add("correct")});if(!ok)e.target.classList.add("wrong");$("#score").textContent=points+"점";$("#feedback").textContent=ok?"정답이에요!":"정답은 "+q.answer+"예요.";$("#feedback").className="feedback "+(ok?"good":"bad");$("#nextQuestion").textContent=qi===9?"결과 보기":"다음 문제";$("#nextQuestion").classList.remove("hidden")};
$("#quizAudio").onclick=()=>{const q=quiz[qi];playSegment(wordPlayer,timings[q.id].word,$("#quizAudio"))};$("#nextQuestion").onclick=()=>{if(qi<9){qi++;showQuestion()}else{stopAudio();$("#quizPlay").classList.add("hidden");$("#quizResult").classList.remove("hidden");$("#resultTitle").textContent=points+"점";$("#resultText").textContent=points>=80?"훌륭해요! 학습한 단어를 잘 기억하고 있어요.":"틀린 단어를 다시 학습한 뒤 한 번 더 도전해 보세요."}};$("#startQuiz").onclick=startQuiz;$("#retryQuiz").onclick=startQuiz;
Promise.all([fetch("words.json").then(r=>r.json()),fetch("assets/audio/audio-timings.json").then(r=>r.json())]).then(([w,t])=>{words=w;timings=t;render()}).catch(()=>{document.body.innerHTML="<p style='padding:30px'>학습 자료를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.</p>"});